various changes

diff --git a/bash/func b/bash/func
--- a/bash/func
+++ b/bash/func
@@ -1,33 +1,52 @@
 #!/bin/bash
 
-the_eye() {
-	if [ $? != 0 ]; then
-		printf "\033[01;31m( O_o) "
-	fi
+# Create a new directory and enter it
+mkd() {
+	mkdir -p "$@" && cd "$_";
 }
 
+# Backup a directory
 backup() {
 	mv $1 $1~
 }
 
-eskel() {
-	cp /usr/portage/skel.ebuild ./$1.ebuild
-	cp /usr/portage/skel.ChangeLog ./ChangeLog
-	cp /usr/portage/skel.metadata.xml ./metadata.xml
-	LC_ALL=C sed -i -e "s/<PACKAGE_NAME>-<PACKAGE_VERSION>-<PACKAGE_RELEASE>/$1/g" \
-		-e "s/DD MMM YYYY/$(date '+%d %b %Y')/g" \
-		-e 's/YOUR_NAME/Matt Adams/g' \
-		-e 's/YOUR_EMAIL/matt@rtvision.com/g' ChangeLog
-	sed -i -e 's/>@rtvision.com/>matt@rtvision.com/g' metadata.xml
+# Determine size of a file or total size of a directory
+fs() {
+	if du -b /dev/null > /dev/null 2>&1; then
+		local arg=-sbh;
+	else
+		local arg=-sh;
+	fi
+	if [[ -n "$@" ]]; then
+		du $arg -- "$@";
+	else
+		du $arg .[^.]* *;
+	fi;
 }
 
-etest() {
-	ebuild $1 unpack && ebuild $1 compile && ebuild $1 install
+# Create a data URL from a file
+dataurl() {
+	local mimeType=$(file -b --mime-type "$1");
+	if [[ $mimeType == text/* ]]; then
+		mimeType="${mimeType};charset=utf-8";
+	fi
+	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
 }
 
-prompt_git() {
-	local s='';
+# Get the short symbolic ref.
+# If HEAD isnt a symbolic ref, get the short SHA for the latest commit
+# Otherwise, just give up.
+git_current_branch() {
 	local branchName='';
+	branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
+	git rev-parse --short HEAD 2> /dev/null || \
+	'(unknown)')";
+	echo $branchName
+}
+
+# Build the git prompt
+git_prompt() {
+	local s='';
 	# Check if the current directory is in a Git repository.
 	if [ $(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}") == '0' ]; then
 		# check if the current directory is in .git before running git checks
@@ -51,17 +70,65 @@ prompt_git() {
 				s+='$';
 			fi;
 		fi;
-		# Get the short symbolic ref.
-		# If HEAD isnt a symbolic ref, get the short SHA for the latest commit
-		# Otherwise, just give up.
-		branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
-		git rev-parse --short HEAD 2> /dev/null || \
-		echo '(unknown)')";
 		[ -n "${s}" ] && s=" [${s}]";
-		echo -e "${1}${branchName}${blue}${s}";
+		echo -e "${1}$(git_current_branch)${blue}${s}";
 	else
 		return;
 	fi;
+}
+
+# Show all the names (CNs and SANs) listed in the SSL certificate for a given domain
+getcertnames() {
+	if [ -z "${1}" ]; then
+		echo "ERROR: No domain specified.";
+		return 1;
+	fi;
+	local domain="${1}";
+	echo "Testing ${domain}…";
+	echo ""; # newline
+	local tmp=$(echo -e "GET / HTTP/1.0\nEOT" \
+		| openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1);
+	if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
+		local certText=$(echo "${tmp}" \
+			| openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, \
+			no_serial, no_sigdump, no_signame, no_validity, no_version");
+		echo "Common Name:";
+		echo ""; # newline
+		echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//";
+		echo ""; # newline
+		echo "Subject Alternative Name(s):";
+		echo ""; # newline
+		echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
+			| sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2;
+		return 0;
+	else
+		echo "ERROR: Certificate not found.";
+		return 1;
+	fi;
+}
+
+# Create an ebuild skeleton
+eskel() {
+	cp /usr/portage/skel.ebuild ./$1.ebuild
+	cp /usr/portage/skel.ChangeLog ./ChangeLog
+	cp /usr/portage/skel.metadata.xml ./metadata.xml
+	LC_ALL=C sed -i -e "s/<PACKAGE_NAME>-<PACKAGE_VERSION>-<PACKAGE_RELEASE>/$1/g" \
+		-e "s/DD MMM YYYY/$(date '+%d %b %Y')/g" \
+		-e 's/YOUR_NAME/Matt Adams/g' \
+		-e 's/YOUR_EMAIL/matt@rtvision.com/g' ChangeLog
+	sed -i -e 's/>@rtvision.com/>matt@rtvision.com/g' metadata.xml
+}
+
+# Test the ebuild
+etest() {
+	ebuild $1 unpack && ebuild $1 compile && ebuild $1 install
+}
+
+# Show eyeballs if previous command didn't exit with success
+eyeballs() {
+	if [ $? != 0 ]; then
+		printf "\033[01;31m( O_o) "
+	fi
 }
 
 # vim: ft=sh
